# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deposito', '0002_remove_campione_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='campione',
            name='frah',
            field=models.CharField(default=0, max_length=10, verbose_name='Codice'),
            preserve_default=False,
        ),
    ]
