# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deposito', '0004_auto_20160315_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campione',
            name='codice',
            field=models.CharField(editable=False, max_length=10, verbose_name='Codice'),
        ),
    ]
