# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deposito', '0005_auto_20160315_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='campione',
            name='BAR',
            field=models.CharField(default='#0', max_length=10),
            preserve_default=False,
        ),
    ]
